#!/usr/bin/env dart
// Generated by Hermes Agent — 2026-05-09
// Mode: implement
// Repo: /home/muszy/projects/rhetoric_lab
//
// Smoke script: signUp → profile bootstrap flow verification
// DEFAULT: dry-run — no Supabase write operations
// Execute mode requires explicit --execute flag (NOT run in this task)

import 'dart:io';

import 'package:supabase_flutter/supabase_flutter.dart';

// =============================================================================
// Exit codes
// =============================================================================
const int exitPass = 0;
const int exitFailed = 1;
const int exitMissingConfig = 2;
const int exitCleanupFailed = 3;
const int exitExecuteNotImplemented = 4;

// =============================================================================
// Mode
// =============================================================================
enum RunMode { dryRun, execute }

class SmokeConfig {
  final String supabaseUrl;
  final String anonKey;
  final String serviceRoleKey;
  final String testEmailDomain;
  final String smokeEmailPrefix;

  const SmokeConfig({
    required this.supabaseUrl,
    required this.anonKey,
    required this.serviceRoleKey,
    required this.testEmailDomain,
    required this.smokeEmailPrefix,
  });

  static SmokeConfig fromEnvironment() {
    return SmokeConfig(
      supabaseUrl: Platform.environment['SUPABASE_URL'] ?? '',
      anonKey: Platform.environment['SUPABASE_ANON_KEY'] ?? '',
      serviceRoleKey: Platform.environment['SUPABASE_SERVICE_ROLE_KEY'] ?? '',
      testEmailDomain:
          Platform.environment['TEST_EMAIL_DOMAIN'] ?? 'example.com',
      smokeEmailPrefix: Platform.environment['SMOKE_EMAIL_PREFIX'] ?? 'smoke',
    );
  }
}

class SmokeIdentity {
  final String email;
  final String displayName;
  final String password;

  const SmokeIdentity({
    required this.email,
    required this.displayName,
    required this.password,
  });
}

// =============================================================================
// Identity generation (unit-testable, no side effects)
// =============================================================================
SmokeIdentity generateSmokeIdentity({
  required String emailPrefix,
  required String emailDomain,
}) {
  final now = DateTime.now();
  final datePart =
      '${now.year}${_pad(now.month)}${_pad(now.day)}-${_pad(now.hour)}${_pad(now.minute)}${_pad(now.second)}';
  final randPart = _randomAlphanumeric(8);
  final email = '$emailPrefix-$datePart-$randPart@$emailDomain';
  final displayName = 'SmokeBot-$datePart-$randPart';
  // Fixed password for smoke testing — not a real credential
  const password = 'smoke-test-password-not-real';
  return SmokeIdentity(
    email: email,
    displayName: displayName,
    password: password,
  );
}

String _pad(int n) => n.toString().padLeft(2, '0');

String _randomAlphanumeric(int length) {
  const chars =
      'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789';
  final rand = DateTime.now().microsecondsSinceEpoch;
  final buf = StringBuffer();
  for (var i = 0; i < length; i++) {
    buf.write(chars[(rand + i * 7) % chars.length]);
  }
  return buf.toString();
}

// =============================================================================
// Precheck results
// =============================================================================
class PrecheckResult {
  final String key;
  final bool present;

  const PrecheckResult({required this.key, required this.present});
}

// =============================================================================
// Output formatting
// =============================================================================
void _log(String tag, String message) {
  // Structured log — tag is [TAG] format, message is human-readable.
  // NO secret values are ever printed.
  print('[$tag] $message');
}

void _logResult(String result) {
  print('[RESULT] $result');
}

// =============================================================================
// Precheck logic (dry-run compatible)
// =============================================================================
List<PrecheckResult> runPrechecks(SmokeConfig config, RunMode mode) {
  final results = <PrecheckResult>[];

  // Env presence checks
  results.add(
    PrecheckResult(key: 'SUPABASE_URL', present: config.supabaseUrl.isNotEmpty),
  );
  results.add(
    PrecheckResult(
      key: 'SUPABASE_ANON_KEY',
      present: config.anonKey.isNotEmpty,
    ),
  );
  results.add(
    PrecheckResult(
      key: 'SUPABASE_SERVICE_ROLE_KEY',
      present: config.serviceRoleKey.isNotEmpty,
    ),
  );

  // Log precheck results
  for (final r in results) {
    _log('PRECHECK', '${r.key}: ${r.present ? "present" : "missing"}');
  }

  // Migration 007 / trigger checks are skipped in dry-run
  if (mode == RunMode.execute) {
    _log('PRECHECK', 'migration_007_verification: planned');
    _log('PRECHECK', 'trigger_on_auth_user_insert: planned');
    _log('PRECHECK', 'auth_settings: planned');
  } else {
    _log('PRECHECK', 'migration_007_verification: skipped_in_dry_run');
    _log('PRECHECK', 'trigger_on_auth_user_insert: skipped_in_dry_run');
    _log('PRECHECK', 'auth_settings: skipped_in_dry_run');
  }

  return results;
}

// =============================================================================
// Validation helpers
// =============================================================================
bool allRequiredEnvPresent(List<PrecheckResult> prechecks) {
  // SUPABASE_URL and SUPABASE_ANON_KEY are hard requirements in both modes.
  // SERVICE_ROLE_KEY is required only in execute mode for cleanup.
  return prechecks
      .where((r) => r.key == 'SUPABASE_URL' || r.key == 'SUPABASE_ANON_KEY')
      .every((r) => r.present);
}

bool serviceRolePresent(List<PrecheckResult> prechecks) {
  return prechecks.any(
    (r) => r.key == 'SUPABASE_SERVICE_ROLE_KEY' && r.present,
  );
}

// =============================================================================
// Execute mode skeleton
// =============================================================================
Future<int> runExecute(SmokeConfig config, SmokeIdentity identity) async {
  // Verify migration 007 function exists
  _log('EXECUTE', 'Would verify handle_new_user function in public schema');
  // TODO: Implement with Supabase SQL query via service role client
  // if not verified, throw UnimplementedError with clear message

  // Verify trigger exists
  _log('EXECUTE', 'Would verify on_auth_user_insert trigger on auth.users');
  // TODO: Implement with Supabase SQL query via service role client

  // Perform signUp
  _log('EXECUTE', 'Would call Supabase Auth signUp for ${identity.email}');
  // TODO: Implement actual signUp:
  // final client = SupabaseClient(config.supabaseUrl, config.anonKey);
  // final session = await client.auth.signUp(
  //   email: identity.email,
  //   password: identity.password,
  //   data: {'display_name': identity.displayName},
  // );
  throw UnimplementedError(
    'Execute mode is not fully implemented. '
    'This is intentional — do NOT run --execute without manual review. '
    'Next step: implement signUp + profile verification + cleanup.',
  );
}

// =============================================================================
// Dry-run mode
// =============================================================================
Future<int> runDryRun(
  SmokeConfig config,
  SmokeIdentity identity,
  List<PrecheckResult> prechecks,
) async {
  _log('MODE', 'dry-run');
  _log(
    'DRY-RUN',
    'Would call signUp with display_name metadata: ${identity.displayName}',
  );
  _log('DRY-RUN', 'Would verify public.profiles row exists after signUp');
  _log('DRY-RUN', 'Would verify profile display_name matches metadata');
  _log('DRY-RUN', 'Would cleanup smoke auth user and profile');

  if (!serviceRolePresent(prechecks)) {
    _log(
      'PRECHECK',
      'SUPABASE_SERVICE_ROLE_KEY: missing — cleanup will be skipped',
    );
  } else {
    _log(
      'DRY-RUN',
      'Cleanup plan: DELETE from auth.users + DELETE from public.profiles',
    );
  }

  return exitPass;
}

// =============================================================================
// Parse arguments
// =============================================================================
(RunMode, String?) parseArgs(List<String> args) {
  RunMode mode = RunMode.dryRun;
  String? error;

  for (final arg in args) {
    switch (arg) {
      case '--dry-run':
        if (mode == RunMode.execute) {
          error = 'Cannot combine --dry-run and --execute';
        } else {
          mode = RunMode.dryRun;
        }
        break;
      case '--execute':
        if (mode == RunMode.dryRun && args.contains('--dry-run')) {
          error = 'Cannot combine --dry-run and --execute';
        } else {
          mode = RunMode.execute;
        }
        break;
      default:
        if (arg.startsWith('--')) {
          print('[WARN] Unknown flag: $arg — ignoring');
        }
    }
  }

  // Reject conflicting flags
  if (args.contains('--dry-run') && args.contains('--execute')) {
    return (RunMode.dryRun, 'Cannot combine --dry-run and --execute');
  }

  return (mode, error);
}

// =============================================================================
// Main
// =============================================================================
Future<int> main(List<String> args) async {
  // Parse mode
  final (mode, argError) = parseArgs(args);
  if (argError != null) {
    _log('ERROR', argError);
    return exitFailed;
  }

  _log('MODE', mode == RunMode.dryRun ? 'dry-run' : 'execute');

  // Load configuration from environment
  final config = SmokeConfig.fromEnvironment();

  // Generate smoke identity
  final identity = generateSmokeIdentity(
    emailPrefix: config.smokeEmailPrefix,
    emailDomain: config.testEmailDomain,
  );
  _log('IDENTITY', 'email=${identity.email}');
  _log('IDENTITY', 'display_name=${identity.displayName}');

  // Run prechecks
  final prechecks = runPrechecks(config, mode);

  // Validate required config
  if (!allRequiredEnvPresent(prechecks)) {
    _log('ERROR', 'Missing required environment variables');
    return exitMissingConfig;
  }

  // Mode-specific run
  if (mode == RunMode.dryRun) {
    final rc = await runDryRun(config, identity, prechecks);
    _logResult(rc == exitPass ? 'DRY_RUN_PASS' : 'DRY_RUN_FAIL');
    return rc;
  } else {
    // Execute mode: check service role requirement first
    if (!serviceRolePresent(prechecks)) {
      _log(
        'ERROR',
        'SUPABASE_SERVICE_ROLE_KEY is required for execute mode cleanup',
      );
      return exitMissingConfig;
    }
    try {
      final rc = await runExecute(config, identity);
      _logResult('EXECUTE_PASS');
      return rc;
    } on UnimplementedError catch (e) {
      _log('ERROR', e.message);
      _logResult('EXECUTE_NOT_IMPLEMENTED');
      return exitExecuteNotImplemented;
    } catch (e) {
      _log('ERROR', 'Unexpected error: $e');
      return exitFailed;
    }
  }
}
